const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("cricketApp", {
  platform: process.platform,
  getConfig: () => ipcRenderer.invoke("config:get"),
  setConfig: (patch) => ipcRenderer.invoke("config:set", patch),
  selectDirectory: (opts) => ipcRenderer.invoke("dialog:select-directory", opts),
  selectDatabaseFile: (opts) => ipcRenderer.invoke("dialog:select-database-file", opts),
  currentDatabase: () => ipcRenderer.invoke("db:current"),
  switchDatabase: (filePath) => ipcRenderer.invoke("db:switch", filePath),
  newDatabase: () => ipcRenderer.invoke("db:new"),
  exportDatabase: () => ipcRenderer.invoke("db:export"),
  saveRecording: (arrayBuffer, defaultName, subfolder) =>
    ipcRenderer.invoke("save-recording", arrayBuffer, defaultName, subfolder),
  ensureRecordingFolder: (folderName) =>
    ipcRenderer.invoke("recordings:ensure-folder", folderName),
  db: {
    teams: () => ipcRenderer.invoke("db:teams"),
    players: (teamId) => ipcRenderer.invoke("db:players", teamId),
    competitions: () => ipcRenderer.invoke("db:competitions"),
    officials: (role) => ipcRenderer.invoke("db:officials", role),
    grounds: () => ipcRenderer.invoke("db:grounds"),
    matchTypes: () => ipcRenderer.invoke("db:matchTypes"),
    masters: (category) => ipcRenderer.invoke("db:masters", category),
    saveMaster: (item) => ipcRenderer.invoke("db:master:save", item),
    deleteMaster: (id) => ipcRenderer.invoke("db:master:delete", id),
    reorderMaster: (category, grp, ids) => ipcRenderer.invoke("db:master:reorder", { category, grp, ids }),
    matches: () => ipcRenderer.invoke("db:matches"),
    getMatch: (id) => ipcRenderer.invoke("db:match:get", id),
    saveTeam: (team) => ipcRenderer.invoke("db:team:save", team),
    deleteTeam: (id) => ipcRenderer.invoke("db:team:delete", id),
    savePlayer: (player) => ipcRenderer.invoke("db:player:save", player),
    deletePlayer: (id) => ipcRenderer.invoke("db:player:delete", id),
    saveOfficial: (o) => ipcRenderer.invoke("db:official:save", o),
    deleteOfficial: (id) => ipcRenderer.invoke("db:official:delete", id),
    saveGround: (g) => ipcRenderer.invoke("db:ground:save", g),
    deleteGround: (id) => ipcRenderer.invoke("db:ground:delete", id),
    saveCompetition: (c) => ipcRenderer.invoke("db:competition:save", c),
    deleteCompetition: (id) => ipcRenderer.invoke("db:competition:delete", id),
    saveMatch: (match) => ipcRenderer.invoke("db:match:save", match),
    saveMatchState: (payload) => ipcRenderer.invoke("db:match:saveState", payload),
    deleteMatch: (id) => ipcRenderer.invoke("db:match:delete", id),
    reportBowling: (matchId) => ipcRenderer.invoke("db:report:bowling", matchId),
    reportBatting: (matchId) => ipcRenderer.invoke("db:report:batting", matchId),
  },
});
